import type { GanttData } from "../types";

export const ACTIVITY_COLORS = [
  { id: "blue", color: "#4361ee", textColor: "#fff", progressColor: "#3046b5" },
  { id: "purple", color: "#7209b7", textColor: "#fff", progressColor: "#570b8a" },
  { id: "pink", color: "#f72585", textColor: "#fff", progressColor: "#c41c6a" },
  { id: "orange", color: "#fb8500", textColor: "#fff", progressColor: "#c96a00" },
  { id: "teal", color: "#2ec4b6", textColor: "#fff", progressColor: "#249c91" },
  { id: "green", color: "#06d6a0", textColor: "#fff", progressColor: "#05ab80" },
  { id: "red", color: "#ef476f", textColor: "#fff", progressColor: "#c73a5a" },
  { id: "indigo", color: "#480ca8", textColor: "#fff", progressColor: "#380a83" },
  { id: "cyan", color: "#00b4d8", textColor: "#fff", progressColor: "#008fac" },
  { id: "amber", color: "#ffb703", textColor: "#333", progressColor: "#cc9202" },
  { id: "lime", color: "#84cc16", textColor: "#fff", progressColor: "#6aa312" },
  { id: "rose", color: "#e11d48", textColor: "#fff", progressColor: "#b4183a" },
];

export function getColorForIndex(index: number) {
  return ACTIVITY_COLORS[index % ACTIVITY_COLORS.length];
}

export const defaultData: GanttData = {
  data: [
    {
      id: 1,
      text: "پروژه نمونه",
      start_date: "2026-02-22",
      duration: 30,
      progress: 0.3,
      open: true,
      type: "project",
      color: "#4361ee",
      textColor: "#fff",
    },
    {
      id: 2,
      text: "فاز اول - برنامه‌ریزی",
      start_date: "2026-02-22",
      duration: 7,
      progress: 0.8,
      parent: 1,
      color: "#7209b7",
      textColor: "#fff",
    },
    {
      id: 3,
      text: "تحلیل نیازمندی‌ها",
      start_date: "2026-02-22",
      duration: 3,
      progress: 1,
      parent: 2,
      color: "#f72585",
      textColor: "#fff",
    },
    {
      id: 4,
      text: "طراحی معماری",
      start_date: "2026-02-25",
      duration: 4,
      progress: 0.6,
      parent: 2,
      color: "#fb8500",
      textColor: "#fff",
    },
    {
      id: 5,
      text: "فاز دوم - توسعه",
      start_date: "2026-03-01",
      duration: 14,
      progress: 0.2,
      parent: 1,
      color: "#2ec4b6",
      textColor: "#fff",
    },
    {
      id: 6,
      text: "پیاده‌سازی رابط کاربری",
      start_date: "2026-03-01",
      duration: 7,
      progress: 0.4,
      parent: 5,
      color: "#06d6a0",
      textColor: "#fff",
    },
    {
      id: 7,
      text: "پیاده‌سازی منطق",
      start_date: "2026-03-08",
      duration: 7,
      progress: 0,
      parent: 5,
      color: "#ef476f",
      textColor: "#fff",
    },
    {
      id: 8,
      text: "فاز سوم - آزمایش",
      start_date: "2026-03-15",
      duration: 7,
      progress: 0,
      parent: 1,
      color: "#480ca8",
      textColor: "#fff",
    },
    {
      id: 9,
      text: "تست واحد",
      start_date: "2026-03-15",
      duration: 4,
      progress: 0,
      parent: 8,
      color: "#00b4d8",
      textColor: "#fff",
    },
    {
      id: 10,
      text: "تحویل نهایی",
      start_date: "2026-03-22",
      duration: 0,
      progress: 0,
      parent: 1,
      type: "milestone",
      color: "#ffb703",
      textColor: "#333",
    },
  ],
  links: [
    { id: 1, source: 3, target: 4, type: "0" },
    { id: 2, source: 4, target: 6, type: "0" },
    { id: 3, source: 6, target: 7, type: "0" },
    { id: 4, source: 7, target: 9, type: "0" },
    { id: 5, source: 9, target: 10, type: "0" },
  ],
};
